//
// Generated by afu_json_mgr from ../../hw/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "afu"
`define AFU_ACCEL_UUID 128'hc8c59ff8_a22c_49f1_851f_a04c1217c7ee
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
